### ISSUE TITLE
Any other audio format supported by Wavenet model (like .mp3) other than .wav?

### ISSUE THREAD

**Issue by DillipKS** [drethage/speech-denoising-wavenet#11]
@drethage Can you clarify if the training/test data needs to be in .wav format or it can support any other format? I have audio data in .mp3 format and converting it to .wav is resource intensive. How can I train and test the wavenet model with data in .mp3 format itself?

**Comment by drethage** [comment]
Hi DillipKS, [PySoundFile](http://pysoundfile.readthedocs.io/en/0.9.0/) is used for reading/writing audio to disk. It supports many audio files, however not mp3. So I would recommend converting your data to .wav. There are many tools available for this: [audio conversion cheat sheet](http://stefaanlippens.net/audio_conversion_cheat_sheet/)

**Comment by jordipons** [comment]
Also, I don't expect the model to work in any other format than .wav, because the model was trained with .wav files. Not because the code cannot digest .mp3 or any other format (you could easily implement that), but because your data would be out of the distribution which the model was trained on. You should retrain the model or transform your files to the same .wav format.
