### ISSUE TITLE
Is there any possibilities to change into Tensorflow model?

### ISSUE THREAD

**Issue by tonyyyye** [drethage/speech-denoising-wavenet#4]
We need to move it into Android, but there is no such interface to read from the checkpoints.

**Comment by jordipons** [comment]
Yes, you can change to Tensorflow since we are using Keras. You just need to switch your back-end!

As noted in the readme.md file, current code was developed under Keras 1.2 and Theano 0.9.0 - since the large dilations present in the architecture were not supported by the 1.2.0 version of Tensorflow that was available then. 

Please, let us know if you find that the current version of Tensorflow (1.4) supports our large dilations!

**Comment by shifaspv** [comment]
The function returns a set of check points while training. which one of those should I takes for testing?.
